#!/usr/bin/env python3
"""Generate web delivery images without modifying source photographs."""
from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
PHOTOS = ROOT / "social" / "photos"
THUMBS = ROOT / "social" / "thumbs"


def save_webp(source: Path, target: Path, max_width: int, quality: int) -> tuple[int, int]:
    opened = Image.open(source)
    try:
        image = ImageOps.exif_transpose(opened).convert("RGB")
        width, height = image.size
        if width > max_width:
            resized_height = round(height * max_width / width)
            image = image.resize((max_width, resized_height), Image.Resampling.LANCZOS)
        target.parent.mkdir(parents=True, exist_ok=True)
        image.save(target, "WEBP", quality=quality, method=6, optimize=True)
        return width, height
    finally:
        opened.close()


def main() -> None:
    save_webp(ROOT / "image.jpg", ROOT / "image-1600.webp", 1600, 72)
    save_webp(ROOT / "omaralfawzan.png", ROOT / "omaralfawzan-240.webp", 240, 78)

    dimensions: list[tuple[int, int]] = []
    for source in sorted(PHOTOS.glob("photo_*.jpg")):
        target = THUMBS / f"{source.stem}.webp"
        dimensions.append(save_webp(source, target, 480, 60))

    rows = ",\n  ".join(f"[{width},{height}]" for width, height in dimensions)
    metadata = (
        "// Generated by scripts/generate_performance_images.py.\n"
        "// Original pixel dimensions preserve gallery layout before thumbnails load.\n"
        f"const PHOTO_DIMENSIONS = Object.freeze([\n  {rows}\n]);\n"
    )
    (ROOT / "social" / "photo-metadata.js").write_text(metadata, encoding="utf-8")
    print(f"Generated {len(dimensions)} gallery thumbnails and 2 shared images.")


if __name__ == "__main__":
    main()
